name: using action from market place

on: push

jobs:
  market_action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code from repository action
        uses: actions/checkout@v4
      - name: Python Syntax Checker
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
