name: using secrets in workflows

on: push

jobs:
  secrets_job:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws checkout credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key-access: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: list s3 buckets
        run: aws s3api list-buckets
